#!/bin/sh

PROGRAM="/home/nikolaib/Projects/sample_python/uart_logger.py"
PIDFILE="/tmp/uart_logger.pid"

msg()
{
	echo $1
	logger $1
}

die()
{
	msg $1
	exit 1
}


start()
{
    	start-stop-daemon -S -x $PROGRAM -b -m -p $PIDFILE -- 
	[ x$? == x0 ] || die "failed to start $PROGRAM"
	msg "$PROGRAM started" 
}

stop()
{
	start-stop-daemon -K -p $PIDFILE -s TERM
	rm -rf $PIDFILE
}

restart()
{
	stop
	start
}

usage()
{
    	msg "$0 (start|stop|restart)"
	exit 1
}

case $1 in
    	start) start ;;
    	stop) stop ;;
    	restart) restart ;;
    	*) usage ;;
esac

exit 0
